SELECT NAME, DETECTED_USAGES, CURRENTLY_USED, FIRST_USAGE_DATE
FROM   DBA_FEATURE_USAGE_STATISTICS
WHERE  VERSION = (SELECT VERSION FROM V$INSTANCE) AND (DETECTED_USAGES > 0 OR CURRENTLY_USED != 'FALSE')
/
