curl -X GET -o 2pc_pending.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/2pc_pending.sql
curl -X GET -o 2pc_transaction.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/2pc_transaction.sql
curl -X GET -o access.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/access.sql
curl -X GET -o active_sess_hist.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/active_sess_hist.sql
curl -X GET -o alerta_wf_sms_ctable.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/alerta_wf_sms_ctable.sql
curl -X GET -o alerta_wf_sms_gerro.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/alerta_wf_sms_gerro.sql
curl -X GET -o alerta_wf_sms.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/alerta_wf_sms.sh
curl -X GET -o alerta_wf_sms.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/alerta_wf_sms.sql
curl -X GET -o analise_conc.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/analise_conc.sh
curl -X GET -o analise_lock.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/analise_lock.sh
curl -X GET -o archive.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/archive.sql
curl -X GET -o asm_info.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/asm_info.sql
curl -X GET -o awr.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/awr.sql
curl -X GET -o awr_sqlplan.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/awr_sqlplan.sql
curl -X GET -o change_ebs_passwd.sql.com_erro https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/change_ebs_passwd.sql.com_erro
curl -X GET -o change_ebs_usr_pass.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/change_ebs_usr_pass.sql
curl -X GET -o checklist.sh.bkp20180121 https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/checklist.sh.bkp20180121
curl -X GET -o coleta_estat_dicionario.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/coleta_estat_dicionario.sh
curl -X GET -o coleta_estatisticas_ecomex.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/coleta_estatisticas_ecomex.sh
curl -X GET -o coleta_estatisticas_msaf.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/coleta_estatisticas_msaf.sh
curl -X GET -o coleta_estatisticas_msaf_teste.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/coleta_estatisticas_msaf_teste.sh
curl -X GET -o coleta_estatisticas.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/coleta_estatisticas.sh
curl -X GET -o conc24hs.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc24hs.sql
curl -X GET -o concbysid.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/concbysid.sql
curl -X GET -o conc_fila.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_fila.sql
curl -X GET -o conc_hist_luis.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_hist_luis.sql
curl -X GET -o conc_hist.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_hist.sql
curl -X GET -o conc_por_dia.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_por_dia.sql
curl -X GET -o conc_por_ger.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_por_ger.sql
curl -X GET -o conc_por_hora.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_por_hora.sql
curl -X GET -o conc_prog.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_prog.sql
curl -X GET -o conc_run2.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_run2.sql
curl -X GET -o conc_run.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_run.sql
curl -X GET -o conc_session.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_session.sql
curl -X GET -o conc.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc.sql
curl -X GET -o concurrent_sid.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/concurrent_sid.sql
curl -X GET -o conc_utilization_per_hour.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_utilization_per_hour.sql
curl -X GET -o consulta_patches_aplicados.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/consulta_patches_aplicados.sql
curl -X GET -o cpu_usage.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/cpu_usage.sql
curl -X GET -o create_user_FUNC_EBS_XPTO.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/create_user_FUNC_EBS_XPTO.sql
curl -X GET -o db_features_usage.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/db_features_usage.sql
curl -X GET -o dblink.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/dblink.sql
curl -X GET -o db_param_analyzer.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/db_param_analyzer.sql
curl -X GET -o Desabilita_Responsabilidades_Usuario.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/Desabilita_Responsabilidades_Usuario.sql
curl -X GET -o desc_conc.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/desc_conc.sql
curl -X GET -o df.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/df.sql
curl -X GET -o dg.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/dg.sql
curl -X GET -o dir.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/dir.sql
curl -X GET -o disk_file_operation.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/disk_file_operation.sql
curl -X GET -o EBS-RESPONSABILIDADE_DE_UM_PARA_OUTRO_USER2.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/EBS-RESPONSABILIDADE_DE_UM_PARA_OUTRO_USER2.sql
curl -X GET -o EBS-RESPONSABILIDADE_DE_UM_USER_PARA_OUTRO_USER2.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/EBS-RESPONSABILIDADE_DE_UM_USER_PARA_OUTRO_USER2.sql
curl -X GET -o ebs_usu_attr.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/ebs_usu_attr.sql
curl -X GET -o ebs_usu_resp.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/ebs_usu_resp.sql
curl -X GET -o ebs_usu.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/ebs_usu.sql
curl -X GET -o exec2.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/exec2.sh
curl -X GET -o exec.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/exec.sh
curl -X GET -o exec_sqltune_report_sessao_1h_1.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/exec_sqltune_report_sessao_1h_1.sql
curl -X GET -o exec_sqltune_report_sessao_1h_2.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/exec_sqltune_report_sessao_1h_2.sql
curl -X GET -o exec_sqltune_sessao_1h_1.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/exec_sqltune_sessao_1h_1.sql
curl -X GET -o exec_sqltune_sessao_1h_2.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/exec_sqltune_sessao_1h_2.sql
curl -X GET -o filaconc2.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/filaconc2.sql
curl -X GET -o filaconcsol.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/filaconcsol.sql
curl -X GET -o filaconc.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/filaconc.sql
curl -X GET -o fila.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/fila.sql
curl -X GET -o fonte.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/fonte.sql
curl -X GET -o fsgrowth.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/fsgrowth.sql
curl -X GET -o gera_kill_apps.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/gera_kill_apps.sql
curl -X GET -o gera_kill_forms.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/gera_kill_forms.sql
curl -X GET -o gera_sqltune_sessao_1h.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/gera_sqltune_sessao_1h.sql
curl -X GET -o header.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/header.sql
curl -X GET -o hparameter.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/hparameter.sql
curl -X GET -o ind.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/ind.sql
curl -X GET -o interconnect.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/interconnect.sql
curl -X GET -o invalid.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/invalid.sql
curl -X GET -o jobs.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/jobs.sql
curl -X GET -o kill_apps.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/kill_apps.sql
curl -X GET -o kill_forms.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/kill_forms.sql
curl -X GET -o kill.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/kill.sql
curl -X GET -o kill_wms_bkp.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/kill_wms_bkp.sql
curl -X GET -o lock_old.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/lock_old.sql
curl -X GET -o lock.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/lock.sql
curl -X GET -o login_fail.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/login_fail.sql
curl -X GET -o longops.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/longops.sql
curl -X GET -o mobile.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/mobile.sql
curl -X GET -o new_lock.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/new_lock.sql
curl -X GET -o next.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/next.sql
curl -X GET -o nlock.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/nlock.sql
curl -X GET -o obj.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/obj.sql
curl -X GET -o orig.coleta_estatisticas_msaf.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/orig.coleta_estatisticas_msaf.sh
curl -X GET -o owner.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/owner.sql
curl -X GET -o patch.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/patch.sql
curl -X GET -o ping_nodes.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/ping_nodes.sh
curl -X GET -o privs.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/privs.sql
curl -X GET -o proc_long.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/proc_long.sql
curl -X GET -o proc.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/proc.sql
curl -X GET -o prof_abril.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/prof_abril.sql
curl -X GET -o profile_diag.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/profile_diag.sql
curl -X GET -o profile.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/profile.sql
curl -X GET -o profile_x.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/profile_x.sql
curl -X GET -o RecFonte1.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/RecFonte1.sql
curl -X GET -o recovery_usage.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/recovery_usage.sql
curl -X GET -o redo.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/redo.sql
curl -X GET -o relat.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/relat.sql
curl -X GET -o seg.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/seg.sql
curl -X GET -o sess_active.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/sess_active.sql
curl -X GET -o session_luis.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/session_luis.sql
curl -X GET -o session_rollback.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/session_rollback.sql
curl -X GET -o session_sid.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/session_sid.sql
curl -X GET -o session.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/session.sql
curl -X GET -o setenv https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/setenv
curl -X GET -o sga_stat.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/sga_stat.sql
curl -X GET -o sid_concurrent.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/sid_concurrent.sql
curl -X GET -o sid.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/sid.sql
curl -X GET -o smart_scan_count.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/smart_scan_count.sql
curl -X GET -o sqlfulltext.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/sqlfulltext.sql
curl -X GET -o sqlplan.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/sqlplan.sql
curl -X GET -o sqltune_sessao_1h.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/sqltune_sessao_1h.sql
curl -X GET -o sqltune.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/sqltune.sql
curl -X GET -o start_workflow.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/start_workflow.sql
curl -X GET -o syn.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/syn.sql
curl -X GET -o tabs2.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/tabs2.sql
curl -X GET -o tab.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/tab.sql
curl -X GET -o tamanhobase.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/tamanhobase.sql
curl -X GET -o tbsusage.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/tbsusage.sql
curl -X GET -o teste.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/teste.sql
curl -X GET -o top_concurrents.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/top_concurrents.sql
curl -X GET -o trace.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/trace.sql
curl -X GET -o ts.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/ts.sql
curl -X GET -o uso_tabsp.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/uso_tabsp.sql
curl -X GET -o utl_test.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/utl_test.sql
curl -X GET -o vapps_login.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/vapps_login.sql
curl -X GET -o verifica_apps_login.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_apps_login.sh
curl -X GET -o verifica_bkp.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_bkp.sh
curl -X GET -o verifica_conc24hs.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_conc24hs.sh
curl -X GET -o verifica_fast_rec_area.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_fast_rec_area.sql
curl -X GET -o verifica_fconc.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_fconc.sh
curl -X GET -o verifica_forms.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_forms.sh
curl -X GET -o verifica_lock_novo.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_lock_novo.sh
curl -X GET -o verifica_lock.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_lock.sh
curl -X GET -o verifica_sessao_1h.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_sessao_1h.sh
curl -X GET -o verifica_sessao_1h.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_sessao_1h.sql
curl -X GET -o verifica_workflow.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_workflow.sh
curl -X GET -o vworkflow.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/vworkflow.sql
curl -X GET -o wfmailer.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/wfmailer.sql
curl -X GET -o wms_session.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/wms_session.sql
curl -X GET -o xplan.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/xplan.sql
curl -X GET -o XXFND_HIST_CONC_REQUESTS_PRC.PRC https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/XXFND_HIST_CONC_REQUESTS_PRC.PRC
