curl -X PUT -T 2pc_pending.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/2pc_pending.sql
curl -X PUT -T 2pc_transaction.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/2pc_transaction.sql
curl -X PUT -T access.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/access.sql
curl -X PUT -T active_sess_hist.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/active_sess_hist.sql
curl -X PUT -T alerta_wf_sms_ctable.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/alerta_wf_sms_ctable.sql
curl -X PUT -T alerta_wf_sms_gerro.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/alerta_wf_sms_gerro.sql
curl -X PUT -T alerta_wf_sms.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/alerta_wf_sms.sh
curl -X PUT -T alerta_wf_sms.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/alerta_wf_sms.sql
curl -X PUT -T analise_conc.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/analise_conc.sh
curl -X PUT -T analise_lock.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/analise_lock.sh
curl -X PUT -T archive.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/archive.sql
curl -X PUT -T asm_info.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/asm_info.sql
curl -X PUT -T awr.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/awr.sql
curl -X PUT -T awr_sqlplan.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/awr_sqlplan.sql
curl -X PUT -T change_ebs_passwd.sql.com_erro https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/change_ebs_passwd.sql.com_erro
curl -X PUT -T change_ebs_usr_pass.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/change_ebs_usr_pass.sql
curl -X PUT -T checklist.sh.bkp20180121 https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/checklist.sh.bkp20180121
curl -X PUT -T coleta_estat_dicionario.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/coleta_estat_dicionario.sh
curl -X PUT -T coleta_estatisticas_ecomex.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/coleta_estatisticas_ecomex.sh
curl -X PUT -T coleta_estatisticas_msaf.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/coleta_estatisticas_msaf.sh
curl -X PUT -T coleta_estatisticas_msaf_teste.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/coleta_estatisticas_msaf_teste.sh
curl -X PUT -T coleta_estatisticas.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/coleta_estatisticas.sh
curl -X PUT -T conc24hs.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc24hs.sql
curl -X PUT -T concbysid.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/concbysid.sql
curl -X PUT -T conc_fila.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_fila.sql
curl -X PUT -T conc_hist_luis.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_hist_luis.sql
curl -X PUT -T conc_hist.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_hist.sql
curl -X PUT -T conc_por_dia.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_por_dia.sql
curl -X PUT -T conc_por_ger.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_por_ger.sql
curl -X PUT -T conc_por_hora.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_por_hora.sql
curl -X PUT -T conc_prog.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_prog.sql
curl -X PUT -T conc_run2.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_run2.sql
curl -X PUT -T conc_run.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_run.sql
curl -X PUT -T conc_session.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_session.sql
curl -X PUT -T conc.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc.sql
curl -X PUT -T concurrent_sid.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/concurrent_sid.sql
curl -X PUT -T conc_utilization_per_hour.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/conc_utilization_per_hour.sql
curl -X PUT -T consulta_patches_aplicados.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/consulta_patches_aplicados.sql
curl -X PUT -T cpu_usage.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/cpu_usage.sql
curl -X PUT -T create_user_FUNC_EBS_XPTO.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/create_user_FUNC_EBS_XPTO.sql
curl -X PUT -T db_features_usage.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/db_features_usage.sql
curl -X PUT -T dblink.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/dblink.sql
curl -X PUT -T db_param_analyzer.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/db_param_analyzer.sql
curl -X PUT -T Desabilita_Responsabilidades_Usuario.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/Desabilita_Responsabilidades_Usuario.sql
curl -X PUT -T desc_conc.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/desc_conc.sql
curl -X PUT -T df.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/df.sql
curl -X PUT -T dg.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/dg.sql
curl -X PUT -T dir.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/dir.sql
curl -X PUT -T disk_file_operation.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/disk_file_operation.sql
curl -X PUT -T EBS-RESPONSABILIDADE_DE_UM_PARA_OUTRO_USER2.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/EBS-RESPONSABILIDADE_DE_UM_PARA_OUTRO_USER2.sql
curl -X PUT -T EBS-RESPONSABILIDADE_DE_UM_USER_PARA_OUTRO_USER2.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/EBS-RESPONSABILIDADE_DE_UM_USER_PARA_OUTRO_USER2.sql
curl -X PUT -T ebs_usu_attr.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/ebs_usu_attr.sql
curl -X PUT -T ebs_usu_resp.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/ebs_usu_resp.sql
curl -X PUT -T ebs_usu.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/ebs_usu.sql
curl -X PUT -T exec.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/exec.sh
curl -X PUT -T exec_sqltune_report_sessao_1h_1.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/exec_sqltune_report_sessao_1h_1.sql
curl -X PUT -T exec_sqltune_report_sessao_1h_2.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/exec_sqltune_report_sessao_1h_2.sql
curl -X PUT -T exec_sqltune_sessao_1h_1.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/exec_sqltune_sessao_1h_1.sql
curl -X PUT -T exec_sqltune_sessao_1h_2.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/exec_sqltune_sessao_1h_2.sql
curl -X PUT -T filaconc2.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/filaconc2.sql
curl -X PUT -T filaconcsol.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/filaconcsol.sql
curl -X PUT -T filaconc.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/filaconc.sql
curl -X PUT -T fila.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/fila.sql
curl -X PUT -T fonte.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/fonte.sql
curl -X PUT -T fsgrowth.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/fsgrowth.sql
curl -X PUT -T gera_kill_apps.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/gera_kill_apps.sql
curl -X PUT -T gera_kill_forms.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/gera_kill_forms.sql
curl -X PUT -T gera_sqltune_sessao_1h.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/gera_sqltune_sessao_1h.sql
curl -X PUT -T header.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/header.sql
curl -X PUT -T hparameter.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/hparameter.sql
curl -X PUT -T ind.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/ind.sql
curl -X PUT -T interconnect.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/interconnect.sql
curl -X PUT -T invalid.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/invalid.sql
curl -X PUT -T jobs.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/jobs.sql
curl -X PUT -T kill_apps.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/kill_apps.sql
curl -X PUT -T kill_forms.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/kill_forms.sql
curl -X PUT -T kill.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/kill.sql
curl -X PUT -T kill_wms_bkp.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/kill_wms_bkp.sql
curl -X PUT -T lock_old.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/lock_old.sql
curl -X PUT -T lock.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/lock.sql
curl -X PUT -T login_fail.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/login_fail.sql
curl -X PUT -T longops.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/longops.sql
curl -X PUT -T mobile.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/mobile.sql
curl -X PUT -T new_lock.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/new_lock.sql
curl -X PUT -T next.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/next.sql
curl -X PUT -T nlock.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/nlock.sql
curl -X PUT -T obj.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/obj.sql
curl -X PUT -T orig.coleta_estatisticas_msaf.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/orig.coleta_estatisticas_msaf.sh
curl -X PUT -T owner.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/owner.sql
curl -X PUT -T patch.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/patch.sql
curl -X PUT -T ping_nodes.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/ping_nodes.sh
curl -X PUT -T privs.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/privs.sql
curl -X PUT -T proc_long.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/proc_long.sql
curl -X PUT -T proc.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/proc.sql
curl -X PUT -T prof_abril.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/prof_abril.sql
curl -X PUT -T profile_diag.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/profile_diag.sql
curl -X PUT -T profile.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/profile.sql
curl -X PUT -T profile_x.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/profile_x.sql
curl -X PUT -T RecFonte1.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/RecFonte1.sql
curl -X PUT -T recovery_usage.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/recovery_usage.sql
curl -X PUT -T redo.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/redo.sql
curl -X PUT -T relat.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/relat.sql
curl -X PUT -T seg.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/seg.sql
curl -X PUT -T sess_active.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/sess_active.sql
curl -X PUT -T session_luis.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/session_luis.sql
curl -X PUT -T session_rollback.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/session_rollback.sql
curl -X PUT -T session_sid.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/session_sid.sql
curl -X PUT -T session.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/session.sql
curl -X PUT -T setenv https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/setenv
curl -X PUT -T sga_stat.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/sga_stat.sql
curl -X PUT -T sid_concurrent.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/sid_concurrent.sql
curl -X PUT -T sid.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/sid.sql
curl -X PUT -T smart_scan_count.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/smart_scan_count.sql
curl -X PUT -T sqlfulltext.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/sqlfulltext.sql
curl -X PUT -T sqlplan.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/sqlplan.sql
curl -X PUT -T sqltune_sessao_1h.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/sqltune_sessao_1h.sql
curl -X PUT -T sqltune.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/sqltune.sql
curl -X PUT -T start_workflow.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/start_workflow.sql
curl -X PUT -T syn.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/syn.sql
curl -X PUT -T tabs2.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/tabs2.sql
curl -X PUT -T tab.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/tab.sql
curl -X PUT -T tamanhobase.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/tamanhobase.sql
curl -X PUT -T tbsusage.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/tbsusage.sql
curl -X PUT -T teste.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/teste.sql
curl -X PUT -T top_concurrents.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/top_concurrents.sql
curl -X PUT -T trace.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/trace.sql
curl -X PUT -T ts.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/ts.sql
curl -X PUT -T uso_tabsp.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/uso_tabsp.sql
curl -X PUT -T utl_test.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/utl_test.sql
curl -X PUT -T vapps_login.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/vapps_login.sql
curl -X PUT -T verifica_apps_login.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_apps_login.sh
curl -X PUT -T verifica_bkp.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_bkp.sh
curl -X PUT -T verifica_conc24hs.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_conc24hs.sh
curl -X PUT -T verifica_fast_rec_area.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_fast_rec_area.sql
curl -X PUT -T verifica_fconc.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_fconc.sh
curl -X PUT -T verifica_forms.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_forms.sh
curl -X PUT -T verifica_lock_novo.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_lock_novo.sh
curl -X PUT -T verifica_lock.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_lock.sh
curl -X PUT -T verifica_sessao_1h.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_sessao_1h.sh
curl -X PUT -T verifica_sessao_1h.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_sessao_1h.sql
curl -X PUT -T verifica_workflow.sh https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/verifica_workflow.sh
curl -X PUT -T vworkflow.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/vworkflow.sql
curl -X PUT -T wfmailer.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/wfmailer.sql
curl -X PUT -T wms_session.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/wms_session.sql
curl -X PUT -T xplan.sql https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/xplan.sql
curl -X PUT -T XXFND_HIST_CONC_REQUESTS_PRC.PRC https://objectstorage.sa-saopaulo-1.oraclecloud.com/p/c-82qBSD9m4irKk-qWHW4BNK-7R4xXwsbrO1Xt3vLHiynYI6tx3nz2w_a3G1g05u/n/grc0jipovivj/b/ATG/o/XXFND_HIST_CONC_REQUESTS_PRC.PRC
